# Generated by Django 4.2 on 2024-05-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=255)),
                ('adresse_fournisseur', models.CharField(max_length=255)),
                ('tel_fournisseur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_magasin', models.CharField(max_length=255)),
                ('num_tel_magasin', models.CharField(max_length=20)),
                ('adresse_magasin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_produit', models.CharField(max_length=100, unique=True)),
                ('poids_produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origine_produit', models.CharField(max_length=100)),
                ('purete_produit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('num_tel_client', models.CharField(max_length=15)),
                ('NIF', models.CharField(max_length=20, unique=True)),
                ('NIS', models.CharField(max_length=20, unique=True)),
                ('Art', models.CharField(max_length=20, unique=True)),
                ('RC', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transformation', models.DateField()),
                ('cout_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_reel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_unitaire_transformer_initial', models.IntegerField()),
                ('nb_unitaire_transformer_final', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.produit')),
            ],
        ),
    ]
