# Generated by Django 4.2 on 2024-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_delete_transformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transformation', models.DateField()),
                ('cout_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_reel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nb_unitaire_transformer_initial', models.IntegerField()),
                ('nb_unitaire_transformer_final', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.produit')),
            ],
        ),
    ]
