# Generated by Django 4.2 on 2024-05-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_atelier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture_vente', models.DateField()),
                ('montant_total_vente_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_facture', models.CharField(max_length=50)),
            ],
        ),
    ]
