# Generated by Django 4.2 on 2024-05-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_factureachat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bijoutier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bijoutier', models.CharField(max_length=255)),
                ('email_bijoutier', models.EmailField(max_length=254)),
                ('mot_de_pass_bijoutier', models.CharField(max_length=255)),
                ('adresse_bijoutier', models.CharField(max_length=255)),
                ('tel_bijoutier', models.CharField(max_length=20)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.atelier')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.magasin')),
            ],
        ),
    ]
