# Generated by Django 4.2 on 2024-05-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_bijoutier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('bijoutier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.bijoutier')),
                ('facture_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.facturevente')),
            ],
        ),
    ]
