# Generated by Django 4.2 on 2024-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_produit_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='reference_produit',
            field=models.CharField(max_length=100),
        ),
    ]
